//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsClient.productservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Electronic", Namespace="http://schemas.datacontract.org/2004/07/AddsService")]
    [System.SerializableAttribute()]
    public partial class Electronic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image1 {
            get {
                return this.Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image1Field, value) != true)) {
                    this.Image1Field = value;
                    this.RaisePropertyChanged("Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image2 {
            get {
                return this.Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image2Field, value) != true)) {
                    this.Image2Field = value;
                    this.RaisePropertyChanged("Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image3 {
            get {
                return this.Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image3Field, value) != true)) {
                    this.Image3Field = value;
                    this.RaisePropertyChanged("Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarAddress {
            get {
                return this.SellarAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarAddressField, value) != true)) {
                    this.SellarAddressField = value;
                    this.RaisePropertyChanged("SellarAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarContact {
            get {
                return this.SellarContactField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarContactField, value) != true)) {
                    this.SellarContactField = value;
                    this.RaisePropertyChanged("SellarContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarName {
            get {
                return this.SellarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarNameField, value) != true)) {
                    this.SellarNameField = value;
                    this.RaisePropertyChanged("SellarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/AddsService")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategorynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategotyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoryname {
            get {
                return this.CategorynameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorynameField, value) != true)) {
                    this.CategorynameField = value;
                    this.RaisePropertyChanged("Categoryname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategotyId {
            get {
                return this.CategotyIdField;
            }
            set {
                if ((this.CategotyIdField.Equals(value) != true)) {
                    this.CategotyIdField = value;
                    this.RaisePropertyChanged("CategotyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/AddsService")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelField, value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image1 {
            get {
                return this.Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image1Field, value) != true)) {
                    this.Image1Field = value;
                    this.RaisePropertyChanged("Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image2 {
            get {
                return this.Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image2Field, value) != true)) {
                    this.Image2Field = value;
                    this.RaisePropertyChanged("Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image3 {
            get {
                return this.Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image3Field, value) != true)) {
                    this.Image3Field = value;
                    this.RaisePropertyChanged("Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarAddress {
            get {
                return this.SellarAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarAddressField, value) != true)) {
                    this.SellarAddressField = value;
                    this.RaisePropertyChanged("SellarAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarContact {
            get {
                return this.SellarContactField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarContactField, value) != true)) {
                    this.SellarContactField = value;
                    this.RaisePropertyChanged("SellarContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarName {
            get {
                return this.SellarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarNameField, value) != true)) {
                    this.SellarNameField = value;
                    this.RaisePropertyChanged("SellarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/AddsService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Image3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sellarAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image1 {
            get {
                return this.Image1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image1Field, value) != true)) {
                    this.Image1Field = value;
                    this.RaisePropertyChanged("Image1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image2 {
            get {
                return this.Image2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image2Field, value) != true)) {
                    this.Image2Field = value;
                    this.RaisePropertyChanged("Image2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image3 {
            get {
                return this.Image3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Image3Field, value) != true)) {
                    this.Image3Field = value;
                    this.RaisePropertyChanged("Image3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarContact {
            get {
                return this.SellarContactField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarContactField, value) != true)) {
                    this.SellarContactField = value;
                    this.RaisePropertyChanged("SellarContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellarName {
            get {
                return this.SellarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SellarNameField, value) != true)) {
                    this.SellarNameField = value;
                    this.RaisePropertyChanged("SellarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sellarAddress {
            get {
                return this.sellarAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.sellarAddressField, value) != true)) {
                    this.sellarAddressField = value;
                    this.RaisePropertyChanged("sellarAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="productservice.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addElectornics", ReplyAction="http://tempuri.org/IService1/addElectornicsResponse")]
        bool addElectornics(AdsClient.productservice.Electronic name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addElectornics", ReplyAction="http://tempuri.org/IService1/addElectornicsResponse")]
        System.Threading.Tasks.Task<bool> addElectornicsAsync(AdsClient.productservice.Electronic name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCategory", ReplyAction="http://tempuri.org/IService1/addCategoryResponse")]
        bool addCategory(AdsClient.productservice.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCategory", ReplyAction="http://tempuri.org/IService1/addCategoryResponse")]
        System.Threading.Tasks.Task<bool> addCategoryAsync(AdsClient.productservice.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCar", ReplyAction="http://tempuri.org/IService1/addCarResponse")]
        bool addCar(AdsClient.productservice.Car cars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addCar", ReplyAction="http://tempuri.org/IService1/addCarResponse")]
        System.Threading.Tasks.Task<bool> addCarAsync(AdsClient.productservice.Car cars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBook", ReplyAction="http://tempuri.org/IService1/addBookResponse")]
        bool addBook(AdsClient.productservice.Book books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBook", ReplyAction="http://tempuri.org/IService1/addBookResponse")]
        System.Threading.Tasks.Task<bool> addBookAsync(AdsClient.productservice.Book books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateElectonics", ReplyAction="http://tempuri.org/IService1/UpdateElectonicsResponse")]
        int UpdateElectonics(AdsClient.productservice.Electronic id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateElectonics", ReplyAction="http://tempuri.org/IService1/UpdateElectonicsResponse")]
        System.Threading.Tasks.Task<int> UpdateElectonicsAsync(AdsClient.productservice.Electronic id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCar", ReplyAction="http://tempuri.org/IService1/UpdateCarResponse")]
        int UpdateCar(AdsClient.productservice.Car id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCar", ReplyAction="http://tempuri.org/IService1/UpdateCarResponse")]
        System.Threading.Tasks.Task<int> UpdateCarAsync(AdsClient.productservice.Car id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        int UpdateBook(AdsClient.productservice.Book id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        System.Threading.Tasks.Task<int> UpdateBookAsync(AdsClient.productservice.Book id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategory", ReplyAction="http://tempuri.org/IService1/getCategoryResponse")]
        bool getCategory(AdsClient.productservice.Category id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCategory", ReplyAction="http://tempuri.org/IService1/getCategoryResponse")]
        System.Threading.Tasks.Task<bool> getCategoryAsync(AdsClient.productservice.Category id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getcar", ReplyAction="http://tempuri.org/IService1/getcarResponse")]
        AdsClient.productservice.Car[] getcar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getcar", ReplyAction="http://tempuri.org/IService1/getcarResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Car[]> getcarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLaptop", ReplyAction="http://tempuri.org/IService1/GetLaptopResponse")]
        AdsClient.productservice.Electronic[] GetLaptop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLaptop", ReplyAction="http://tempuri.org/IService1/GetLaptopResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetLaptopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMobile", ReplyAction="http://tempuri.org/IService1/GetMobileResponse")]
        AdsClient.productservice.Electronic[] GetMobile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMobile", ReplyAction="http://tempuri.org/IService1/GetMobileResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetMobileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        AdsClient.productservice.Book[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Book[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetElectronics", ReplyAction="http://tempuri.org/IService1/GetElectronicsResponse")]
        AdsClient.productservice.Electronic[] GetElectronics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetElectronics", ReplyAction="http://tempuri.org/IService1/GetElectronicsResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetElectronicsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetoneCar", ReplyAction="http://tempuri.org/IService1/GetoneCarResponse")]
        AdsClient.productservice.Car GetoneCar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetoneCar", ReplyAction="http://tempuri.org/IService1/GetoneCarResponse")]
        System.Threading.Tasks.Task<AdsClient.productservice.Car> GetoneCarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletcar", ReplyAction="http://tempuri.org/IService1/deletcarResponse")]
        string deletcar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletcar", ReplyAction="http://tempuri.org/IService1/deletcarResponse")]
        System.Threading.Tasks.Task<string> deletcarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteElectronics", ReplyAction="http://tempuri.org/IService1/deleteElectronicsResponse")]
        string deleteElectronics(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteElectronics", ReplyAction="http://tempuri.org/IService1/deleteElectronicsResponse")]
        System.Threading.Tasks.Task<string> deleteElectronicsAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AdsClient.productservice.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AdsClient.productservice.IService1>, AdsClient.productservice.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addElectornics(AdsClient.productservice.Electronic name) {
            return base.Channel.addElectornics(name);
        }
        
        public System.Threading.Tasks.Task<bool> addElectornicsAsync(AdsClient.productservice.Electronic name) {
            return base.Channel.addElectornicsAsync(name);
        }
        
        public bool addCategory(AdsClient.productservice.Category category) {
            return base.Channel.addCategory(category);
        }
        
        public System.Threading.Tasks.Task<bool> addCategoryAsync(AdsClient.productservice.Category category) {
            return base.Channel.addCategoryAsync(category);
        }
        
        public bool addCar(AdsClient.productservice.Car cars) {
            return base.Channel.addCar(cars);
        }
        
        public System.Threading.Tasks.Task<bool> addCarAsync(AdsClient.productservice.Car cars) {
            return base.Channel.addCarAsync(cars);
        }
        
        public bool addBook(AdsClient.productservice.Book books) {
            return base.Channel.addBook(books);
        }
        
        public System.Threading.Tasks.Task<bool> addBookAsync(AdsClient.productservice.Book books) {
            return base.Channel.addBookAsync(books);
        }
        
        public int UpdateElectonics(AdsClient.productservice.Electronic id) {
            return base.Channel.UpdateElectonics(id);
        }
        
        public System.Threading.Tasks.Task<int> UpdateElectonicsAsync(AdsClient.productservice.Electronic id) {
            return base.Channel.UpdateElectonicsAsync(id);
        }
        
        public int UpdateCar(AdsClient.productservice.Car id) {
            return base.Channel.UpdateCar(id);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCarAsync(AdsClient.productservice.Car id) {
            return base.Channel.UpdateCarAsync(id);
        }
        
        public int UpdateBook(AdsClient.productservice.Book id) {
            return base.Channel.UpdateBook(id);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBookAsync(AdsClient.productservice.Book id) {
            return base.Channel.UpdateBookAsync(id);
        }
        
        public bool getCategory(AdsClient.productservice.Category id) {
            return base.Channel.getCategory(id);
        }
        
        public System.Threading.Tasks.Task<bool> getCategoryAsync(AdsClient.productservice.Category id) {
            return base.Channel.getCategoryAsync(id);
        }
        
        public AdsClient.productservice.Car[] getcar() {
            return base.Channel.getcar();
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Car[]> getcarAsync() {
            return base.Channel.getcarAsync();
        }
        
        public AdsClient.productservice.Electronic[] GetLaptop() {
            return base.Channel.GetLaptop();
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetLaptopAsync() {
            return base.Channel.GetLaptopAsync();
        }
        
        public AdsClient.productservice.Electronic[] GetMobile() {
            return base.Channel.GetMobile();
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetMobileAsync() {
            return base.Channel.GetMobileAsync();
        }
        
        public AdsClient.productservice.Book[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Book[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public AdsClient.productservice.Electronic[] GetElectronics() {
            return base.Channel.GetElectronics();
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Electronic[]> GetElectronicsAsync() {
            return base.Channel.GetElectronicsAsync();
        }
        
        public AdsClient.productservice.Car GetoneCar(int Id) {
            return base.Channel.GetoneCar(Id);
        }
        
        public System.Threading.Tasks.Task<AdsClient.productservice.Car> GetoneCarAsync(int Id) {
            return base.Channel.GetoneCarAsync(Id);
        }
        
        public string deletcar(int Id) {
            return base.Channel.deletcar(Id);
        }
        
        public System.Threading.Tasks.Task<string> deletcarAsync(int Id) {
            return base.Channel.deletcarAsync(Id);
        }
        
        public string deleteElectronics(int Id) {
            return base.Channel.deleteElectronics(Id);
        }
        
        public System.Threading.Tasks.Task<string> deleteElectronicsAsync(int Id) {
            return base.Channel.deleteElectronicsAsync(Id);
        }
    }
}
